var a = 1;
var b = 280;

var mql1 = window.matchMedia('all and (max-width: 992px)');
if (mql1.matches) {
    b = 150;
} 

var mql2 = window.matchMedia('all and (max-width: 576px)');
if (mql2.matches) {
    b = 80;
}

$(window).scroll(function() {




    if ($(window).scrollTop() > b) {        
        $('.menu').css('top', '0');
        $('.top_menu .cont_services').css('height', '0');
    } else {
        $('.menu').css('top', '-700px');
        $('.top_menu .cont_services').css('height', 'auto');
    }
    if ($(window).scrollTop() > -1&&a==1) {
    	$('.fixed_button').css('position', 'fixed');
    	$('.fixed_button').css('top', 'auto');
    	$('.fixed_button').css('bottom', '220px');
    }
    else {
    	$('.fixed_button').css('position', 'absolute');
    	$('.fixed_button').css('top', '-800px');
    }
  
});

$('.fixed_button img').on('click', function() {
	$('.message_cont').css('position', 'fixed');
	$('.message_cont').css('z-index', '100');
	$('.message').css('height', 'auto');
	$('.message').css('top', '0');
	$('.fixed_button').css('top', '-800px');
	a=0;
});

$('.message_cont').on('click', function() {
	$('.message_cont').css('position', 'absolute');
	$('.message_cont').css('z-index', '-1000');
	$('.message').css('hight', '0');	
	$('.fixed_button').css('position', 'fixed');
    $('.fixed_button').css('top', 'auto');
    $('.fixed_button').css('bottom', '220px');
    a=1;
});



$('.services_fifth_cont_01').on('click', function() {
  if ($('.services_fifth_cont_01 .plus').text() == '+') { 
    $('.services_fifth_hiden_01').css('height', 'auto');
    $('.services_fifth_hiden_01').css('max-height', '9999px');
    $('.services_fifth_cont_01 .plus').html('-');
    $('.services_fifth_cont_01').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_01").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_02').on('click', function() {
  if ($('.services_fifth_cont_02 .plus').text() == '+') { 
    $('.services_fifth_hiden_02').css('height', 'auto');
    $('.services_fifth_hiden_02').css('max-height', '9999px');
    $('.services_fifth_cont_02 .plus').html('-');
    $('.services_fifth_cont_02').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_02").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_03').on('click', function() {
  if ($('.services_fifth_cont_03 .plus').text() == '+') { 
    $('.services_fifth_hiden_03').css('height', 'auto');
    $('.services_fifth_hiden_03').css('max-height', '9999px');
    $('.services_fifth_cont_03 .plus').html('-');
    $('.services_fifth_cont_03').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_03").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_1').on('click', function() {
  if ($('.services_fifth_cont_1 .plus').text() == '+') { 
    $('.services_fifth_hiden_1').css('height', 'auto');
    $('.services_fifth_hiden_1').css('max-height', '9999px');
    $('.services_fifth_cont_1 .plus').html('-');
    $('.services_fifth_cont_1').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_1").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_2').on('click', function() {
  if ($('.services_fifth_cont_2 .plus').text() == '+') { 
    $('.services_fifth_hiden_2').css('height', 'auto');
    $('.services_fifth_hiden_2').css('max-height', '9999px');
    $('.services_fifth_cont_2 .plus').html('-');
    $('.services_fifth_cont_2').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_2").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_3').on('click', function() {
  if ($('.services_fifth_cont_3 .plus').text() == '+') { 
    $('.services_fifth_hiden_3').css('height', 'auto');
    $('.services_fifth_hiden_3').css('max-height', '9999px');
    $('.services_fifth_cont_3 .plus').html('-');
    $('.services_fifth_cont_3').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_3").offset().top - 100);     
  }
  else {
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_4').on('click', function() {
  if ($('.services_fifth_cont_4 .plus').text() == '+') { 
    $('.services_fifth_hiden_4').css('height', 'auto');
    $('.services_fifth_hiden_4').css('max-height', '9999px');
    $('.services_fifth_cont_4 .plus').html('-');
    $('.services_fifth_cont_4').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_4").offset().top - 100);  
  }
  else {
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_5').on('click', function() {
  if ($('.services_fifth_cont_5 .plus').text() == '+') { 
    $('.services_fifth_hiden_5').css('height', 'auto');
    $('.services_fifth_hiden_5').css('max-height', '9999px');
    $('.services_fifth_cont_5 .plus').html('-');
    $('.services_fifth_cont_5').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_5").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_6').on('click', function() {
  if ($('.services_fifth_cont_6 .plus').text() == '+') { 
    $('.services_fifth_hiden_6').css('height', 'auto');
    $('.services_fifth_hiden_6').css('max-height', '9999px');
    $('.services_fifth_cont_6 .plus').html('-');
    $('.services_fifth_cont_6').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_6").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_7').on('click', function() {
  if ($('.services_fifth_cont_7 .plus').text() == '+') { 
    $('.services_fifth_hiden_7').css('height', 'auto');
    $('.services_fifth_hiden_7').css('max-height', '9999px');
    $('.services_fifth_cont_7 .plus').html('-');
    $('.services_fifth_cont_7').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_7").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_8').on('click', function() {
  if ($('.services_fifth_cont_8 .plus').text() == '+') { 
    $('.services_fifth_hiden_8').css('height', 'auto');
    $('.services_fifth_hiden_8').css('max-height', '9999px');
    $('.services_fifth_cont_8 .plus').html('-');
    $('.services_fifth_cont_8').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_8").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_9').on('click', function() {
  if ($('.services_fifth_cont_9 .plus').text() == '+') { 
    $('.services_fifth_hiden_9').css('height', 'auto');
    $('.services_fifth_hiden_9').css('max-height', '9999px');
    $('.services_fifth_cont_9 .plus').html('-');
    $('.services_fifth_cont_9').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_9").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_10').on('click', function() {
  if ($('.services_fifth_cont_10 .plus').text() == '+') { 
    $('.services_fifth_hiden_10').css('height', 'auto');
    $('.services_fifth_hiden_10').css('max-height', '9999px');
    $('.services_fifth_cont_10 .plus').html('-');
    $('.services_fifth_cont_10').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_10").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_11').on('click', function() {
  if ($('.services_fifth_cont_11 .plus').text() == '+') { 
    $('.services_fifth_hiden_11').css('height', 'auto');
    $('.services_fifth_hiden_11').css('max-height', '9999px');
    $('.services_fifth_cont_11 .plus').html('-');
    $('.services_fifth_cont_11').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_11").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_12').on('click', function() {
  if ($('.services_fifth_cont_12 .plus').text() == '+') { 
    $('.services_fifth_hiden_12').css('height', 'auto');
    $('.services_fifth_hiden_12').css('max-height', '9999px');
    $('.services_fifth_cont_12 .plus').html('-');
    $('.services_fifth_cont_12').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_12").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_13').on('click', function() {
  if ($('.services_fifth_cont_13 .plus').text() == '+') { 
    $('.services_fifth_hiden_13').css('height', 'auto');
    $('.services_fifth_hiden_13').css('max-height', '9999px');
    $('.services_fifth_cont_13 .plus').html('-');
    $('.services_fifth_cont_13').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_13").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
}  
});

$('.services_fifth_cont_14').on('click', function() {
  if ($('.services_fifth_cont_14 .plus').text() == '+') { 
    $('.services_fifth_hiden_14').css('height', 'auto');
    $('.services_fifth_hiden_14').css('max-height', '9999px');
    $('.services_fifth_cont_14 .plus').html('-');
    $('.services_fifth_cont_14').css('background-color', 'rgb(225, 190, 133)');
    $('.services_fifth_hiden_01').css('height', '0');
    $('.services_fifth_hiden_01').css('max-height', '0');
    $('.services_fifth_cont_01 .plus').html('+');
    $('.services_fifth_cont_01').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_02').css('height', '0');
    $('.services_fifth_hiden_02').css('max-height', '0');
    $('.services_fifth_cont_02 .plus').html('+');
    $('.services_fifth_cont_02').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_03').css('height', '0');
    $('.services_fifth_hiden_03').css('max-height', '0');
    $('.services_fifth_cont_03 .plus').html('+');
    $('.services_fifth_cont_03').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_2').css('height', '0');
    $('.services_fifth_hiden_2').css('max-height', '0');
    $('.services_fifth_cont_2 .plus').html('+');
    $('.services_fifth_cont_2').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_3').css('height', '0');
    $('.services_fifth_hiden_3').css('max-height', '0');
    $('.services_fifth_cont_3 .plus').html('+');
    $('.services_fifth_cont_3').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_4').css('height', '0');
    $('.services_fifth_hiden_4').css('max-height', '0');
    $('.services_fifth_cont_4 .plus').html('+');
    $('.services_fifth_cont_4').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_5').css('height', '0');
    $('.services_fifth_hiden_5').css('max-height', '0');
    $('.services_fifth_cont_5 .plus').html('+');
    $('.services_fifth_cont_5').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_6').css('height', '0');
    $('.services_fifth_hiden_6').css('max-height', '0');
    $('.services_fifth_cont_6 .plus').html('+');
    $('.services_fifth_cont_6').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_7').css('height', '0');
    $('.services_fifth_hiden_7').css('max-height', '0');
    $('.services_fifth_cont_7 .plus').html('+');
    $('.services_fifth_cont_7').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_8').css('height', '0');
    $('.services_fifth_hiden_8').css('max-height', '0');
    $('.services_fifth_cont_8 .plus').html('+');
    $('.services_fifth_cont_8').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_9').css('height', '0');
    $('.services_fifth_hiden_9').css('max-height', '0');
    $('.services_fifth_cont_9 .plus').html('+');
    $('.services_fifth_cont_9').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_10').css('height', '0');
    $('.services_fifth_hiden_10').css('max-height', '0');
    $('.services_fifth_cont_10 .plus').html('+');
    $('.services_fifth_cont_10').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_11').css('height', '0');
    $('.services_fifth_hiden_11').css('max-height', '0');
    $('.services_fifth_cont_11 .plus').html('+');
    $('.services_fifth_cont_11').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_12').css('height', '0');
    $('.services_fifth_hiden_12').css('max-height', '0');
    $('.services_fifth_cont_12 .plus').html('+');
    $('.services_fifth_cont_12').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_13').css('height', '0');
    $('.services_fifth_hiden_13').css('max-height', '0');
    $('.services_fifth_cont_13 .plus').html('+');
    $('.services_fifth_cont_13').css('background-color', 'rgb(21, 77, 113)');
    $('.services_fifth_hiden_1').css('height', '0');
    $('.services_fifth_hiden_1').css('max-height', '0');
    $('.services_fifth_cont_1 .plus').html('+');
    $('.services_fifth_cont_1').css('background-color', 'rgb(21, 77, 113)');
    $("html").scrollTop($(".services_fifth_cont_14").offset().top - 100);      
  }
  else {
    $('.services_fifth_hiden_14').css('height', '0');
    $('.services_fifth_hiden_14').css('max-height', '0');
    $('.services_fifth_cont_14 .plus').html('+');
    $('.services_fifth_cont_14').css('background-color', 'rgb(21, 77, 113)');
}  
});